/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.orange.ui;

import com.orange.controller.IController;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author niuyunyun
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFramef
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mScrollPanel = new javax.swing.JScrollPane();
        mTree = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mTreeMouseClicked(evt);
            }
        });
        mScrollPanel.setViewportView(mTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /***********************************************self begin**********************************/
    private IController mController;
    private DefaultMutableTreeNode mRoot;
    public void init()
    {
        setTitle("局域网通信助手");
        initTree();
    }
    
    private void initTree()
    {
        mRoot = new DefaultMutableTreeNode("局域网在线成员");
        DefaultTreeModel model = new DefaultTreeModel(mRoot);
        model.setRoot(mRoot);
        mTree.setModel(model);
    }
    
    public void addMember(String member)
    {
        DefaultMutableTreeNode item = new DefaultMutableTreeNode(member);
        mRoot.add(item);
    }
      /***********************************************self end**********************************/
    
    private void mTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mTreeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mTreeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane mScrollPanel;
    private javax.swing.JTree mTree;
    // End of variables declaration//GEN-END:variables
}
